force-app/main/default/objects/EinsteinGPTConfig__c/EinsteinGPTConfig__c.object-meta.xml
<CustomObject>
    <label>EinsteinGPTConfig</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EinsteinGPTConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MessageHistory__c/MessageHistory__c.object-meta.xml
<CustomObject>
    <description>Keep the conversation history</description>
    <label>MessageHistory</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MessageHistories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MessageHistory__c/fields/AiMessage__c.field-meta.xml
<CustomField>
    <fullName>AiMessage__c</fullName>
    <label>AiMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MessageHistory__c/fields/EinsteinGPTConfig__c.field-meta.xml
<CustomField>
    <fullName>EinsteinGPTConfig__c</fullName>
    <label>EinsteinGPTConfig</label>
    <referenceTo>EinsteinGPTConfig__c</referenceTo>
    <relationshipLabel>MessageHistories</relationshipLabel>
    <relationshipName>MessageHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MessageHistory__c/fields/UserMessage__c.field-meta.xml
<CustomField>
    <fullName>UserMessage__c</fullName>
    <label>UserMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EinsteinGPTHistoryController.cls
public with sharing class EinsteinGPTHistoryController {
    @AuraEnabled(cacheable=false)
    public static void addMessageToConfig(Id configId, String usermessage, String aimessage) {
        try {
            MessageHistory__c newMessage = new MessageHistory__c(
                EinsteinGPTConfig__c = configId,
                AiMessage__c = aimessage,
                UserMessage__c = usermessage
            );
            insert newMessage;
        } catch (DmlException e) {
            throw new AuraHandledException('Error while adding the message to config: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<MessageHistory__c> loadMessagesFromConfig(Id configId) {
        try {
            List<MessageHistory__c> histories = [
                SELECT AiMessage__c, UserMessage__c
                FROM MessageHistory__c
                WHERE EinsteinGPTConfig__c = :configId
                ORDER BY CreatedDate ASC
            ];
            return histories;
        } catch (QueryException e) {
            throw new AuraHandledException('Error while loading messages from config: ' + e.getMessage());
        }
    }

 @AuraEnabled
    public static void deleteMessagesFromConfig(Id configId) {
        try {
            List<MessageHistory__c> messagesToDelete = [
                SELECT Id
                FROM MessageHistory__c
                WHERE EinsteinGPTConfig__c = :configId
            ];

            if (!messagesToDelete.isEmpty()) {
                delete messagesToDelete;
            }
        } catch (DmlException e) {
            throw new AuraHandledException('Error while deleting messages from config: ' + e.getMessage());
        }
    }
}