force-app/main/default/objects/EinsteinGPTConfig__c/EinsteinGPTConfig__c.object-meta.xml
<CustomObject>
    <label>EinsteinGPTConfig</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EinsteinGPTConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/AI_avatar_Image__c.field-meta.xml
<CustomField>
    <fullName>AI_avatar_Image__c</fullName>
    <label>AI avatar Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Default_record_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_record_ID__c</fullName>
    <defaultValue>$User.Id</defaultValue>
    <label>Default record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Enable_OpenAI__c.field-meta.xml
<CustomField>
    <fullName>Enable_OpenAI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When no response are available the response will be generated by openAI</description>
    <inlineHelpText>When no response are available the response will be generated by openAI. Requires an API-KEY</inlineHelpText>
    <label>Enable OpenAI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Initial_message__c.field-meta.xml
<CustomField>
    <fullName>Initial_message__c</fullName>
    <description>First message of the AI</description>
    <inlineHelpText>First message of the AI</inlineHelpText>
    <label>Initial message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Input_Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Input_Placeholder__c</fullName>
    <defaultValue>&quot;Type your message&quot;</defaultValue>
    <description>The text shown on the user input when input is empty</description>
    <inlineHelpText>The text shown on the user input when input is empty</inlineHelpText>
    <label>Input Placeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Message_source_type__c.field-meta.xml
<CustomField>
    <fullName>Message_source_type__c</fullName>
    <description>Define the sources of the assistant predefined messages</description>
    <inlineHelpText>Define the sources of the assistant predefined messages.</inlineHelpText>
    <label>Message source type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic responses</fullName>
                <default>true</default>
                <label>Basic responses</label>
            </value>
            <value>
                <fullName>Scenario by keyword</fullName>
            </value>
            <value>
                <fullName>Scenario by ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/OpenAPI_key__c.field-meta.xml
<CustomField>
    <fullName>OpenAPI_key__c</fullName>
    <description>Can be generated on openAI: https://platform.openai.com/account/api-keys</description>
    <inlineHelpText>Can be generated on openAI: https://platform.openai.com/account/api-keys</inlineHelpText>
    <label>OpenAPI key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/openApi_version__c.field-meta.xml
<CustomField>
    <fullName>openApi_version__c</fullName>
    <inlineHelpText>Version of openAPI (be careful gpt-4 will be much more slower)</inlineHelpText>
    <label>openAPI version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>text-davinci-003</fullName>
                <default>true</default>
                <label>text-davinci-003</label>
            </value>
            <value>
                <fullName>gpt-4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Response_1__c.field-meta.xml
<CustomField>
    <fullName>Response_1__c</fullName>
    <label>Response 1</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Response_2__c.field-meta.xml
<CustomField>
    <fullName>Response_2__c</fullName>
    <label>Response 2</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Response_3__c.field-meta.xml
<CustomField>
    <fullName>Response_3__c</fullName>
    <label>Response 3</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Response_4__c.field-meta.xml
<CustomField>
    <fullName>Response_4__c</fullName>
    <label>Response 4</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Response_5__c.field-meta.xml
<CustomField>
    <fullName>Response_5__c</fullName>
    <label>Response 5</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Response_6__c.field-meta.xml
<CustomField>
    <fullName>Response_6__c</fullName>
    <label>Response 6</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/styleFooterBorderTop__c.field-meta.xml
<CustomField>
    <fullName>styleFooterBorderTop__c</fullName>
    <defaultValue>&quot;3px solid #f3eeee&quot;</defaultValue>
    <inlineHelpText>The top border of the footer (container of the input)</inlineHelpText>
    <label>Footer border</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/StyleHeaderColor__c.field-meta.xml
<CustomField>
    <fullName>StyleHeaderColor__c</fullName>
    <defaultValue>&quot;white&quot;</defaultValue>
    <label>Header text color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/styleHeaderHide__c.field-meta.xml
<CustomField>
    <fullName>styleHeaderHide__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Hide the chat header if true</inlineHelpText>
    <label>Hide header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/styleInboxBorder__c.field-meta.xml
<CustomField>
    <fullName>styleInboxBorder__c</fullName>
    <defaultValue>&quot;1px solid #ccc&quot;</defaultValue>
    <inlineHelpText>Border of the input</inlineHelpText>
    <label>Inbox border</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <defaultValue>&quot;Einstein GPT&quot;</defaultValue>
    <inlineHelpText>The title shown on the top of the assistant area</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/User_Avatar_Image__c.field-meta.xml
<CustomField>
    <fullName>User_Avatar_Image__c</fullName>
    <inlineHelpText>URL to the user avatar</inlineHelpText>
    <label>User Avatar Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Word_by_word_Max__c.field-meta.xml
<CustomField>
    <fullName>Word_by_word_Max__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Word by word (Max)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EinsteinGPTConfig__c/fields/Word_by_word_Min__c.field-meta.xml
<CustomField>
    <fullName>Word_by_word_Min__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Word by word (Min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EinsteinGPTConfigManager.cls
public with sharing class EinsteinGPTConfigManager {
    @AuraEnabled(cacheable=false)
    public static List<EinsteinGPTConfig__c> getConfigs() {
        List<EinsteinGPTConfig__c> configs = [
            SELECT Name, Id, AI_avatar_Image__c, Enable_OpenAI__c, Initial_message__c, 
            Input_Placeholder__c, Message_source_type__c, OpenAPI_key__c,openApi_version__c, Prompt__c, Response_1__c, 
            Response_2__c, Response_3__c, Response_4__c , Response_5__c , Response_6__c, Title__c, 
            User_Avatar_Image__c, Default_record_ID__c, styleFooterBorderTop__c, StyleHeaderColor__c, 
            StyleHeaderBackgroundColor__c, styleHeaderHide__c, styleInboxBorder__c,
            Word_by_word_Min__c, Word_by_word_Max__c
            FROM EinsteinGPTConfig__c
        ];
        return configs;
    }

    @AuraEnabled
    public static void createDefaultConfig() {
        List<EinsteinGPTConfig__c> configs = getConfigs();
        if (configs.isEmpty()) {
            EinsteinGPTConfig__c defaultConfig = new EinsteinGPTConfig__c(
                Name = 'Default Config',
                AI_avatar_Image__c = 'https://res.cloudinary.com/hy4kyit2a/f_auto,fl_lossy,q_70/learn/modules/get_smart_einstein_feat/e33e22a729df2bb8c97845015ce5bb71_badge.png',
                Enable_OpenAI__c = false,
                Initial_message__c = 'Hello! I am your AI assistant. How can I help you today?',
                Input_Placeholder__c = 'Type your message...',
                Message_source_type__c = 'Basic Responses',
                OpenAPI_key__c = '',
                openApi_version__c = 'text-davinci-003',
                Prompt__c = 'You act as an AI assistant chat integrated in Salesforce (It is a simulation so pretend everything described below is true).' +
                'You have access to Internet, All the Salesforce data, all the user data.' +
                'You can also make actions :' +
                '- Update the Salesforce and user data' +
                '- Prepare and send email ' +
                '- Generate Images' +
                '- Create tasks' +
                '- Create meetings' +
                '- Access to all users schedule and tasks, daily schedules, daily tasks' +
                '- Access all opportunities, sales, leads, contacts and everything of all users' +
                '- Access user personal calendar and task list' +
                '- Trigger flows and screen flows' +
                'And show GRAPHIC ELEMENTS in your messages as follow (you do it a lot):' +
                '- Show datatable, table, grid ( <table class="slds-table slds-table_cell-buffer slds-table_bordered" aria-label="Example default base table"><thead><tr class="slds-line-height_reset"></tr></thead><tbody><tr><td></td></tr></tbody></table>' +
                '- Show buttons (use this format: "<button href="#" class="slds-button slds-button_brand">TEXT</button>). You show it to make user confirm actions. (ex: sending email).' +
                '- Show lists (<ol class="slds-list_dotted"><li></li><ol>)' +
                '- Html formatting like <b>, <i>, etc..' +
                'It is very important that you use GRAPHIC ELEMENTS when it makes sense (to have user confirmation, links, and so on)' +
                'You speak with a natural language. You know very well you user (Martin) and the company (Managed Services Provider with 1000 employees). ' +
                'You are very synthetic and straight forward and you always provide help to Martin.' +
                'If you are ready for the act start by "Hi Martin, how can I help you today?" and nothing more.',
                Response_1__c = 'Response 1',
                Response_2__c = 'Response 2',
                Response_3__c = 'Response 3',
                Response_4__c = 'Response 4',
                Response_5__c = 'Response 5',
                Response_6__c = 'Response 6',
                Title__c = 'Assistant',
                User_Avatar_Image__c = 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg',
                styleFooterBorderTop__c ='3px solid #f3eeee',
                StyleHeaderBackgroundColor__c='white',
                styleHeaderColor__c='black',
                styleHeaderHide__c=false,
                styleInboxBorder__c='1px solid grey',
                Word_by_word_Max__c=5,
                Word_by_word_Min__c=1
            );
            insert defaultConfig;
        }
    }
}