force-app/main/default/objects/Scenario__c/Scenario__c.object-meta.xml
<CustomObject>
    <description>An EinsteinGPT scenario.
Scenario can be configure in the component to display the related messages</description>
    <label>Scenario</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scenario__c/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <inlineHelpText>Keyword to trigger the scenario</inlineHelpText>
    <label>Keyword</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/ScenarioMessage__c.object-meta.xml
<CustomObject>
    <description>The messages related to a scenario.
It will be used by the component to show the messages of the selected scenario.</description>
    <label>ScenarioMessage</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ScenarioMessages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScenarioMessage__c/fields/ActionAfterAiMessage__c.field-meta.xml
<CustomField>
    <fullName>ActionAfterAiMessage__c</fullName>
    <label>Action after AI message</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Open Email Composer</fullName>
            </value>
            <value>
                <fullName>Execute a flow</fullName>
            </value>
            <value>
                <fullName>Redirect the user</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/AiMessage__c.field-meta.xml
<CustomField>
    <fullName>AiMessage__c</fullName>
    <description>Reply from the AI</description>
    <inlineHelpText>Reply from the AI</inlineHelpText>
    <label>AiMessage</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/Email_Global_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Global_Action_Name__c</fullName>
    <defaultValue>&quot;SDO_Send_Email&quot;</defaultValue>
    <label>Email Global Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/FlowName__c.field-meta.xml
<CustomField>
    <fullName>FlowName__c</fullName>
    <description>If there is a value, the flow is trigger after AI message (using flow API name)</description>
    <inlineHelpText>If there is a value, the flow is trigger after AI message</inlineHelpText>
    <label>FlowName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/Global_Action_Body__c.field-meta.xml
<CustomField>
    <fullName>Global_Action_Body__c</fullName>
    <inlineHelpText>Predifined value for the email body</inlineHelpText>
    <label>Global Action Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/Global_Action_Subject__c.field-meta.xml
<CustomField>
    <fullName>Global_Action_Subject__c</fullName>
    <inlineHelpText>The predefined value for subject</inlineHelpText>
    <label>Global Action Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/Global_Action_To__c.field-meta.xml
<CustomField>
    <fullName>Global_Action_To__c</fullName>
    <inlineHelpText>Predefined value for &quot;To&quot; field of the email</inlineHelpText>
    <label>Global Action To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order of the message in the conversation</description>
    <inlineHelpText>The order of the message in the conversation</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/RedirectURL__c.field-meta.xml
<CustomField>
    <fullName>RedirectURL__c</fullName>
    <description>If there is a value, the user is redirected to the URL after AI message (and after flow execution if there is one)</description>
    <inlineHelpText>If there is a value, the user is redirected to the URL after AI message (and after flow execution if there is one)</inlineHelpText>
    <label>RedirectURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/Scenario__c.field-meta.xml
<CustomField>
    <fullName>Scenario__c</fullName>
    <label>Scenario</label>
    <referenceTo>Scenario__c</referenceTo>
    <relationshipLabel>ScenarioMessages</relationshipLabel>
    <relationshipName>ScenarioMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScenarioMessage__c/fields/UserMessage__c.field-meta.xml
<CustomField>
    <fullName>UserMessage__c</fullName>
    <description>The initial message by the user. It can be used to automatically generate the conversation or to be informative.</description>
    <inlineHelpText>The message from the user before AI response.</inlineHelpText>
    <label>UserMessage</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/ScenarioMessageElement__c.object-meta.xml
<CustomObject>
    <description>The scenario elements complement the message depending on the record type
 Each record type uses it&apos;s specific attributes</description>
    <label>ScenarioMessageElement</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ScenarioMessageElements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScenarioMessageElement__c/fields/badge_Style__c.field-meta.xml
<CustomField>
    <fullName>badge_Style__c</fullName>
    <label>badge_Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>neutral</fullName>
                <default>true</default>
                <label>neutral</label>
            </value>
            <value>
                <fullName>brand</fullName>
            </value>
            <value>
                <fullName>outline-brand</fullName>
            </value>
            <value>
                <fullName>destructive</fullName>
            </value>
            <value>
                <fullName>text-destructive</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/badge_Title__c.field-meta.xml
<CustomField>
    <fullName>badge_Title__c</fullName>
    <label>badge_Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/button_Flow__c.field-meta.xml
<CustomField>
    <fullName>button_Flow__c</fullName>
    <description>The flow to be executed when the button is clicked</description>
    <inlineHelpText>The flow API name to be executed when the button is clicked. (Prevent redirection)</inlineHelpText>
    <label>button_Flow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/Button_Style__c.field-meta.xml
<CustomField>
    <fullName>Button_Style__c</fullName>
    <label>Button_Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>neutral</fullName>
                <default>true</default>
                <label>neutral</label>
            </value>
            <value>
                <fullName>brand</fullName>
            </value>
            <value>
                <fullName>outline-brand</fullName>
            </value>
            <value>
                <fullName>destructive</fullName>
            </value>
            <value>
                <fullName>text-destructive</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/button_Text__c.field-meta.xml
<CustomField>
    <fullName>button_Text__c</fullName>
    <defaultValue>&quot;Label&quot;</defaultValue>
    <inlineHelpText>The button label</inlineHelpText>
    <label>button_Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/button_Url__c.field-meta.xml
<CustomField>
    <fullName>button_Url__c</fullName>
    <defaultValue>&quot;#&quot;</defaultValue>
    <inlineHelpText>The URL the user is redirected to (if button flow is empty)</inlineHelpText>
    <label>button_Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/datatable_Table__c.field-meta.xml
<CustomField>
    <fullName>datatable_Table__c</fullName>
    <inlineHelpText>title1,title2,title3
value-a1,value-a2,value-a3
value-b1,value-b2,value-b3</inlineHelpText>
    <label>datatable_Table</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/html_Content__c.field-meta.xml
<CustomField>
    <fullName>html_Content__c</fullName>
    <description>https://www.lightningdesignsystem.com/components/overview/x</description>
    <inlineHelpText>You can define your own element here. Refer to the design system (https://www.lightningdesignsystem.com/components/overview/) to create Salesforce standard elements.</inlineHelpText>
    <label>html_Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/image_URL__c.field-meta.xml
<CustomField>
    <fullName>image_URL__c</fullName>
    <label>image_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/loading_Text__c.field-meta.xml
<CustomField>
    <fullName>loading_Text__c</fullName>
    <label>loading_Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/loading_TextAfter__c.field-meta.xml
<CustomField>
    <fullName>loading_TextAfter__c</fullName>
    <label>loading_TextAfter</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/loading_Wait__c.field-meta.xml
<CustomField>
    <fullName>loading_Wait__c</fullName>
    <defaultValue>500</defaultValue>
    <inlineHelpText>Wait time in milliseconds</inlineHelpText>
    <label>loading_Wait</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <referenceTo>ScenarioMessage__c</referenceTo>
    <relationshipLabel>ScenarioMessageElements</relationshipLabel>
    <relationshipName>ScenarioMessageElements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/redirection_actionName__c.field-meta.xml
<CustomField>
    <fullName>redirection_actionName__c</fullName>
    <inlineHelpText>Record: view, edit or clone
Object: list, new, tab</inlineHelpText>
    <label>redirection_actionName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>view</fullName>
            </value>
            <value>
                <fullName>edit</fullName>
            </value>
            <value>
                <fullName>clone</fullName>
            </value>
            <value>
                <fullName>list</fullName>
            </value>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>tab</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/redirection_objectApiName__c.field-meta.xml
<CustomField>
    <fullName>redirection_objectApiName__c</fullName>
    <inlineHelpText>Your object API Name (eg: Account)</inlineHelpText>
    <label>redirection_objectApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/redirection_pageName__c.field-meta.xml
<CustomField>
    <fullName>redirection_pageName__c</fullName>
    <label>redirection_ pageName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>home</fullName>
                <default>true</default>
                <label>home</label>
            </value>
            <value>
                <fullName>chatter</fullName>
            </value>
            <value>
                <fullName>today</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/tile_Subtitle__c.field-meta.xml
<CustomField>
    <fullName>tile_Subtitle__c</fullName>
    <label>tile_Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/tile_SubtitleURL__c.field-meta.xml
<CustomField>
    <fullName>tile_SubtitleURL__c</fullName>
    <label>tile_SubtitleURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/tile_Text__c.field-meta.xml
<CustomField>
    <fullName>tile_Text__c</fullName>
    <label>tile_Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/tile_Title__c.field-meta.xml
<CustomField>
    <fullName>tile_Title__c</fullName>
    <label>tile_Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/tile_TitleURL__c.field-meta.xml
<CustomField>
    <fullName>tile_TitleURL__c</fullName>
    <defaultValue>&quot;#&quot;</defaultValue>
    <label>tile_TitleURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScenarioMessageElement__c/fields/tile_URL__c.field-meta.xml
<CustomField>
    <fullName>tile_URL__c</fullName>
    <defaultValue>&quot;#&quot;</defaultValue>
    <label>tile_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AiAssistantMessageController.cls
public with sharing class AiAssistantMessageController {
    @AuraEnabled(cacheable=false)
    public static List<Map<String, Object>> getScenarioMessages() {
        List<Scenario__c> scenarios = [
            SELECT Name, Id, Keyword__c
            FROM Scenario__c
        ];

        List<Map<String, Object>> data = new List<Map<String, Object>>();

        for (Scenario__c scenario : scenarios) {    
            Id scenarioId = scenario.Id;
            List<ScenarioMessage__c> messages = [
                SELECT Id, UserMessage__c, AiMessage__c, FlowName__c, RedirectURL__c, Order__c, ActionAfterAiMessage__c, Email_Global_Action_Name__c, Global_Action_Body__c, Global_Action_Subject__c, Global_Action_To__c,
                    (SELECT Id, RecordTypeId, RecordType.Name, image_URL__c,
                     button_Text__c, button_Url__c, button_Flow__c, button_Style__c, 
                     tile_Title__c, tile_TitleURL__c, tile_Subtitle__c, tile_SubtitleURL__c, tile_Text__c, tile_URL__c, badge_Style__c, 
                     badge_Title__c, datatable_Table__c, loading_Text__c, loading_Wait__c, loading_TextAfter__c, Order__c, html_Content__c,
                     redirection_pageName__c, redirection_actionName__c, redirection_objectApiName__c, redirection_RecordId__c, redirection_Type__c		
                        FROM ScenarioMessageElements__r
                        ORDER BY Order__c)
                FROM ScenarioMessage__c
                WHERE Scenario__c = :scenarioId
                ORDER BY Order__c ASC
            ];

            Map<String, Object> scenarioData = new Map<String, Object>{
                'scenario' => scenario,
                'messages' => messages
            };

            data.add(scenarioData);
        }
        return data;
    }
}